name: Generate and submit documentation
on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t testing_doc .

    - name: Generate documentation
      run: docker run --rm -v $PWD:/home/generate-documentation-automatically testing_doc make doc

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
        message: "Update documentation"