name: Generate and submit documentation
on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Create Docker cache
      id: cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Load Docker cache
      uses: docker/load-cache@v1
      with:
        path: /tmp/.buildx-cache

    - name: Build Docker image
      run: |
        docker buildx build \
        --cache-from=type=local,src=/tmp/.buildx-cache \
        --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache \
        -f docker/Dockerfile -t testing_doc .

    - name: Save Docker cache
      uses: docker/save-cache@v1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

    - name: Generate documentation
      run: docker run --rm -v $PWD:/home/generate-documentation-automatically testing_doc make doc

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
        message: "Update documentation"