name: Generate and submit documentation
on:
  push:
    branches: [main]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t testing_doc .

    - name: Generate documentation
      run: docker run --rm -v $PWD:/home/generate-documentation-automatically testing_doc make doc

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update documentation"
        add: "docs/html/"
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_KEY_TEST }}

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_KEY_TEST }}