name: Generate and submit documentation
on:
  push:
    branches: [main]

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t testing_doc .

    - name: Generate documentation
      run: docker run --rm -v $PWD:/home/generate-documentation-automatically testing_doc make doc

    - name: Commit changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.SECRET_KEY_TEST }}
        message: "Update documentation"
        add: "docs/html/"

    - name: Push changes
      uses: rickstaa/action-create-tag@v1
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main